apiVersion: apps/v1
kind: Deployment
metadata:
  name: extracting
  labels:
    app: extracting
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: extracting
  template:
    metadata:
      labels:
        app: extracting
    spec:
      containers:
      - name: cvltextracting
        image: extractingcontainerregistry.azurecr.io/cvltextracting:11.sp27.103564
        command: [/sbin/init]
        ports:
        - containerPort: 22000
        resources:
          requests:
            memory: 512M
            cpu: 128m
        securityContext:
          privileged: true
        startupProbe:
          httpGet:
            path: /CvContentPreviewGenApp
            port: 22000
          initialDelaySeconds: 20
          periodSeconds: 10
        env:
          - name: ESSERVERIP
            value: "20.96.149.129"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - extracting
            topologyKey: "kubernetes.io/hostname"            
---
apiVersion: v1
kind: Service
metadata:
  name: extracting
spec:
  type: LoadBalancer
  selector:
    app: extracting
  ports:
    - port: 80 
      targetPort: 22000
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: extracting
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: extracting
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Pods
        value: 2
        periodSeconds: 60
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
